### ISSUE TITLE
Validate cardboard lidar cover

### ISSUE THREAD

**Issue by dmalawey** [CAST2022/CAST#1]
Let's review LIDAR measurements.
1) Can we get an explanation of how the Lidar samples are taken as of 2/34?
2) Please share how your prototype cover is used, and why this is necessary at this stage.
3) Please add a link to the file which control the lidar samples

Reference [youtube test video](https://youtu.be/A6CPlSUSw1E?list=PLxU24ZnFDi6z1EAg5RTBa9gfiPB4_u0_O)

**Comment by Edgar-Mac** [comment]
1. I have left comments on the updated Lidar program to further explain the programs functionality. 
2. The cover is used to provide control walls for the lidar. We know the distance of the walls from the lidar so we filter out those values, in turn eliminating the viewpoints we are not interested in at this stage. This allows us to obtain distance data from front of the lidar, where the table will be read, with minimum potential for faulty readings.
3. [Lidar Sample Controller](https://github.com/CAST2022/CAST/blob/Master/Software/Robot/L2_lidar.py)

- Edgar Macias
- CAST - System Integration Engineer

**Comment by dmalawey** [comment]
We need your explanation of how the lidar readings angles are defined, and what they mean when the lidar unit is mounted on your robot.   I have added questions to [your video](https://photos.app.goo.gl/eoudZqrW8TdNx4zt5)

**Comment by kennethgrau** [comment]
Confirmed lidar angles are defined according to the diagram below. Output from our L1 code will be a 360 item array where the index is theta and values are distance readings. From there the readings can be processed further.

![image](https://user-images.githubusercontent.com/98132794/163309782-cc61652c-1911-428c-8a0f-61f6ee916274.png)

That being said, I think we can get rid of the "reference walls"
