### ISSUE TITLE
UV Dosage Variable

### ISSUE THREAD

**Issue by donaldb1226** [CAST2022/CAST#3]
Line 63 in code: Please make the threshold value a variable that can be easily changed at the very top of the program. This will just make editing the program later a lot easier for future engineering work.

**Comment by CAST2022** [comment]
This has been resolved. The GitHub should be updated with these changes.

Thanks,


*Covid Autonomous Sanitization Technology*
Texas A&M University | ***@***.***
Drew Dudney | Software Engineer | Class of 2022
