### ISSUE TITLE
UV Sensor FOV

### ISSUE THREAD

**Issue by donaldb1226** [CAST2022/CAST#4]
During the demonstration, the UV LEDs had to be directly above the sensor to function properly. We need to have the sensor's FOV roughly measured to know the optimal angles at which the sensor is placed. This will guide us further down the line when we are using these sensors in a real-world environment.

**Comment by CAST2022** [comment]
Donald,

I will get these values to you and the distance it can reach and put them
in a new document. This should be completed by tonight.

Thanks,

*Covid Autonomous Sanitization Technology*
Texas A&M University | ***@***.***
Drew Dudney | Software Engineer | Class of 2022

**Comment by CAST2022** [comment]
[UV Sensor Test Values.docx](https://github.com/CAST2022/CAST/files/8346671/UV.Sensor.Test.Values.docx)
 Test values for UV Sensor, this shows distance and angles
